title: An Introduction to Solving Biological Problems with Galaxy
description: with a focus on RNA-Seq analysis using a case study
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
